name: 🐳 Backend Only CI/CD

on:
  push:
    branches: [ main ]

jobs:
  # Backend Deployment
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./axiomBackend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/axiom-backend:${{ github.sha }}
    
    - name: Create simple frontend
      run: |
        mkdir -p frontend-dist
        cat > frontend-dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Axiom Platform</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
                .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                h1 { color: #333; text-align: center; }
                .status { background: #4CAF50; color: white; padding: 10px; border-radius: 5px; text-align: center; margin: 20px 0; }
                .api-info { background: #f0f0f0; padding: 20px; border-radius: 5px; margin: 20px 0; }
                .btn { background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 Axiom Platform</h1>
                <div class="status">✅ Platform is LIVE!</div>
                
                <div class="api-info">
                    <h3>🔧 Backend API Status</h3>
                    <p><strong>Docker Image:</strong> aasheeta8913/axiom-backend:latest</p>
                    <p><strong>API Endpoint:</strong> /api/*</p>
                    <p><strong>Health Check:</strong> /health</p>
                    <button class="btn" onclick="checkHealth()">Check API Health</button>
                </div>
                
                <div class="api-info">
                    <h3>🌐 Deployment Info</h3>
                    <p><strong>CI/CD:</strong> GitHub Actions ✅</p>
                    <p><strong>Registry:</strong> Docker Hub ✅</p>
                    <p><strong>Database:</strong> MongoDB + Redis ✅</p>
                </div>
                
                <div id="health-result"></div>
            </div>
            
            <script>
                async function checkHealth() {
                    const result = document.getElementById('health-result');
                    try {
                        const response = await fetch('/health');
                        const data = await response.json();
                        result.innerHTML = '<div class="status">✅ Backend is Healthy: ' + data.message + '</div>';
                    } catch (error) {
                        result.innerHTML = '<div style="background: #f44336; color: white; padding: 10px; border-radius: 5px;">❌ Backend not accessible from frontend</div>';
                    }
                }
            </script>
        </body>
        </html>
        EOF
    
    - name: Deploy simple frontend to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend-dist
    
    - name: Create production docker-compose
      run: |
        cat > docker-compose.prod.yml << EOF
        version: '3.8'
        
        services:
          backend:
            image: ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest
            ports:
              - "5000:5000"
            environment:
              - NODE_ENV=production
              - MONGODB_URI=mongodb://mongodb:27017/axiom
              - REDIS_URL=redis://redis:6379
              - JWT_SECRET=your-production-secret-change-this
              - PORT=5000
            depends_on:
              - mongodb
              - redis
            restart: unless-stopped
          
          frontend:
            image: nginx:alpine
            ports:
              - "3000:80"
            volumes:
              - ./frontend-dist:/usr/share/nginx/html:ro
            restart: unless-stopped
          
          mongodb:
            image: mongo:7.0
            ports:
              - "27017:27017"
            environment:
              - MONGO_INITDB_DATABASE=axiom
            volumes:
              - mongodb_data:/data/db
            restart: unless-stopped
          
          redis:
            image: redis:7.2-alpine
            ports:
              - "6379:6379"
            command: redis-server --appendonly yes
            volumes:
              - redis_data:/data
            restart: unless-stopped
        
        volumes:
          mongodb_data:
          redis_data:
        EOF
    
    - name: Create deployment script
      run: |
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        echo "🚀 Deploying Axiom Platform..."
        
        # Pull latest images
        docker-compose -f docker-compose.prod.yml pull
        
        # Stop existing containers
        docker-compose -f docker-compose.prod.yml down
        
        # Start new containers
        docker-compose -f docker-compose.prod.yml up -d
        
        echo "✅ Deployment complete!"
        echo "🌐 Frontend: http://localhost:3000"
        echo "🔧 Backend: http://localhost:5000"
        echo "📊 Health: http://localhost:5000/health"
        echo "🐳 Docker: aasheeta8913/axiom-backend:latest"
        echo "🌍 GitHub Pages: https://aasheeta-webxpress.github.io/axiom"
        EOF
        chmod +x deploy.sh
    
    - name: Commit deployment files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docker-compose.prod.yml deploy.sh
        git commit -m "Add backend-only deployment files" || exit 0
        git push

  # Health Check
  health-check:
    needs: deploy-backend
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check Docker Hub image
      run: |
        echo "🐳 Checking Docker Hub image..."
        echo "Image: ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest"
        echo "Available at: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/axiom-backend"
    
    - name: Notify success
      if: success()
      run: |
        echo "🎉 Backend CI/CD Complete!"
        echo "🐳 Docker Hub: ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest"
        echo "🌐 GitHub Pages: https://aasheeta-webxpress.github.io/axiom"
        echo "📋 Ready for deployment!"
