name: ðŸš€ Complete Axiom CI/CD

on:
  push:
    branches: [ main ]

jobs:
  # Backend Deployment
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./axiomBackend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/axiom-backend:${{ github.sha }}

  # Frontend Deployment to GitHub Pages
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Install Flutter dependencies
      run: |
        cd axiom
        flutter pub get
    
    - name: Build Flutter web
      run: |
        cd axiom
        flutter build web --release
        # Create .nojekyll for GitHub Pages
        touch build/web/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./axiom/build/web
        cname: axiom.aasheeta-webxpress.github.io

  # Create Production Deployment Files
  create-deployment:
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create production docker-compose
      run: |
        cat > docker-compose.prod.yml << EOF
        version: '3.8'
        
        services:
          backend:
            image: ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest
            ports:
              - "5000:5000"
            environment:
              - NODE_ENV=production
              - MONGODB_URI=mongodb://mongodb:27017/axiom
              - REDIS_URL=redis://redis:6379
              - JWT_SECRET=your-production-secret
            depends_on:
              - mongodb
              - redis
            restart: unless-stopped
          
          frontend:
            image: nginx:alpine
            ports:
              - "3000:80"
            volumes:
              - ./axiom/build/web:/usr/share/nginx/html:ro
            restart: unless-stopped
          
          mongodb:
            image: mongo:7.0
            ports:
              - "27017:27017"
            environment:
              - MONGO_INITDB_DATABASE=axiom
            volumes:
              - mongodb_data:/data/db
            restart: unless-stopped
          
          redis:
            image: redis:7.2-alpine
            ports:
              - "6379:6379"
            command: redis-server --appendonly yes
            volumes:
              - redis_data:/data
            restart: unless-stopped
        
        volumes:
          mongodb_data:
          redis_data:
        EOF
    
    - name: Create deployment script
      run: |
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        echo "ðŸš€ Deploying Axiom Platform..."
        
        # Pull latest images
        docker-compose -f docker-compose.prod.yml pull
        
        # Stop existing containers
        docker-compose -f docker-compose.prod.yml down
        
        # Start new containers
        docker-compose -f docker-compose.prod.yml up -d
        
        echo "âœ… Deployment complete!"
        echo "ðŸŒ Frontend: http://localhost:3000"
        echo "ðŸ”§ Backend: http://localhost:5000"
        echo "ðŸ“Š Health: http://localhost:5000/health"
        echo "ðŸŒ Live: https://axiom.aasheeta-webxpress.github.io"
        EOF
        chmod +x deploy.sh
    
    - name: Commit deployment files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docker-compose.prod.yml deploy.sh
        git commit -m "Add complete CI/CD deployment files" || exit 0
        git push

  # Health Check
  health-check:
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Wait for deployment
      run: sleep 30
    
    - name: Check Docker Hub image
      run: |
        curl -f "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/axiom-backend/tags/" || echo "Backend image check"
    
    - name: Notify success
      if: success()
      run: |
        echo "ðŸŽ‰ Axiom CI/CD Pipeline Complete!"
        echo "ðŸ³ Backend: ${{ secrets.DOCKER_USERNAME }}/axiom-backend:latest"
        echo "ðŸŒ Frontend: https://axiom.aasheeta-webxpress.github.io"
        echo "ðŸ“‹ Ready for production deployment!"
